### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import pandas as pd

# Set styles for DataFrame styling
# References: https://pandas.pydata.org/pandas-docs/stable/user_guide/style.html#Table-styles
# CSS Styles scraped from Example Solution: https://oregon.bootcampcontent.com/Oregon_Coding_Bootcamp/uofo-por-data-pt-06-2020-u-c/blob/master/02-Homework/04-Pandas/HeroesOfPymoli/HeroesOfPymoli_starter.ipynb
styles = [
    dict(selector='th', props=[('font-family', '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Noto Sans", Ubuntu, Cantarell, "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"'),
                               ('font-size', '1.25rem'),
                               ('border-collapse', 'collapse'),
                               ('border-spacing','0'),
                               ('color', '#2e2e2e'),
                               ('box-sizing', 'border-box'),
                               ('text-align', 'left'),
                               ('border', '1px solid #dfdfdf'),
                               ('padding', '10px 16px'),
                               ('line-height', '20px'),
                               ('vertical-align', 'middle'),
                               ('background-color', '#fafafa'),
                               ('font-weight', '400'),
                               ('border-bottom', 'solid 2px #ccc')]),
    dict(selector='td', props=[('font-family',  '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Noto Sans", Ubuntu, Cantarell, "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"'),
                               ('font-size', '1.25rem'),
                               ('font-weight',  '400'),
                               ('text-align',  'left'),
                               ('border-collapse',  'collapse'),
                               ('border-spacing',  '0'),
                               ('color',  '#2e2e2e'),
                               ('box-sizing',  'border-box'),
                               ('border',  '1px solid #dfdfdf'),
                               ('padding',  '10px 16px'),
                               ('line-height',  '20px'),
                               ('vertical-align',  'middle'),
                               ('background-color', '#ffffff'),
                               ('border-color',  '#dfdfdf')])]

# File to Load (Remember to Change These)
file_to_load = "Resources/purchase_data.csv"

# Read Purchasing File and store into Pandas data frame
purchase_data = pd.read_csv(file_to_load)

## Player Count

* Display the total number of players

In [2]:
# Calculate number of unique player screen names
unique_players = purchase_data['SN'].nunique()

# Put total into DataFrame to display
total_players = pd.DataFrame({'Total Players': [unique_players]})

# Display total number of players with applied style
total_players.head().style.set_table_styles(styles)

## Purchasing Analysis (Total)

* Run basic calculations to obtain number of unique items, average price, etc.


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [3]:
# Run calculations for columns
unique_items = purchase_data['Item ID'].nunique()
avg_price = purchase_data['Price'].mean()
purchases_count = purchase_data['Purchase ID'].count()
total_revenue = purchase_data['Price'].sum()

# Create summary data frame with results
total_analysis = pd.DataFrame({'Number of Unique Items': [unique_items],
                                  'Average Price': [avg_price],
                                  'Number of Purchases': [purchases_count],
                                  'Total Revenue': [total_revenue]})

# Clean data formatting for currency columns
total_analysis['Average Price'] = total_analysis['Average Price'].astype(float).map('${:,.2f}'.format)
total_analysis['Total Revenue'] = total_analysis['Total Revenue'].astype(float).map('${:,.2f}'.format)

# Display Purchasing Analysis (Total) frame with applied style
total_analysis.head().style.set_table_styles(styles)

## Gender Demographics

* Percentage and Count of Male Players


* Percentage and Count of Female Players


* Percentage and Count of Other / Non-Disclosed

In [4]:
# Create DataFrame with just SN and Gender column data
player_genders = purchase_data[['SN','Gender']]

# Drop duplicates since pandas doesn't have a bloody select distinct rows equivalent. oh sure you can perform join functions
# SUPER FAST BUT WHEN IT COMES TO QUICKLY PULLING DISTINCT VALUES YOU HAVE TO DANCE THE MACARENA OR SOMETHING!
# code sample found at: http://www.datasciencemadesimple.com/get-unique-values-rows-dataframe-python-pandas/
unique_genders = player_genders.drop_duplicates()

# Calculate counts and percentage
gender_count = unique_genders['Gender'].value_counts()
total_unique_players = gender_count.sum()
gender_percent = (gender_count / total_unique_players) * 100

# Create DataFrame with Total Count of unique SN per gender group and percentage
gender_demo = pd.DataFrame({'Total Count': gender_count,
                            'Percentage of Players': gender_percent})

# Clean data formatting for percentage columns
gender_demo['Percentage of Players'] = gender_demo['Percentage of Players'].astype(float).map('{:,.2f}%'.format)

# As a precaution: sort DataFrame as descending on Total Count and reset index
gender_demo.sort_values('Total Count', ascending=False).reset_index(drop=True)

# Display Gender Demographics frame with applied style
gender_demo.head().style.set_table_styles(styles)


## Purchasing Analysis (Gender)

* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. by gender




* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [5]:
# Create DataFrame with Purchase ID, SN, Price column data and group by Gender
gender_purchases = purchase_data[['Purchase ID','SN','Gender','Price']].groupby(['Gender'])

# Calculate counts, mean, sum and count of unique players for Average Total Purchase
gender_purchase_count = gender_purchases['Purchase ID'].count()
gender_avg_purchase = gender_purchases['Price'].mean()
gender_total_purchase = gender_purchases['Price'].sum()
gender_unique_players = gender_purchases['SN'].nunique()
gender_avg_total = gender_total_purchase / gender_unique_players

# Create Purchasing Analysis DataFrame
gender_analysis = pd.DataFrame({'Purchase Count': gender_purchase_count,
                                'Average Purchase Price': gender_avg_purchase,
                                'Total Purchase Value': gender_total_purchase,
                                'Avg Total Purchase per Person': gender_avg_total})

# Clean data formatting for currency columns
gender_analysis['Average Purchase Price'] = gender_analysis['Average Purchase Price'].astype(float).map(
    '${:,.2f}'.format)
gender_analysis['Total Purchase Value'] = gender_analysis['Total Purchase Value'].astype(float).map(
    '${:,.2f}'.format)
gender_analysis['Avg Total Purchase per Person'] = gender_analysis['Avg Total Purchase per Person'].astype(float).map(
    '${:,.2f}'.format)

# Display Purchasing Analysis frame with applied style
gender_analysis.style.set_table_styles(styles)

## Age Demographics

* Establish bins for ages


* Categorize the existing players using the age bins. Hint: use pd.cut()


* Calculate the numbers and percentages by age group


* Create a summary data frame to hold the results


* Optional: round the percentage column to two decimal points


* Display Age Demographics Table

In [6]:
# Create bins and labels
age_bins = [0, 9, 14, 19, 24, 29, 34, 39, 50]
bin_labels = ['<10','10-14','15-19','20-24','25-29','30-34','35-39','40+']

# Add the new Age Ranges column using bins/labels
purchase_data['Age Ranges'] = pd.cut(purchase_data['Age'], bins=age_bins, labels=bin_labels, include_lowest=True)

# Create DataFrame with just SN and Age Ranges
player_ages = purchase_data[['SN','Age Ranges']]

# Drop duplicates
# code sample found at: http://www.datasciencemadesimple.com/get-unique-values-rows-dataframe-python-pandas/
unique_ages = player_ages.drop_duplicates()

# Calculate counts and percentage
age_count = unique_ages['Age Ranges'].value_counts()
age_players = age_count.sum()
age_percent = (age_count / age_players) * 100

# Create DataFrame with Total Count of unique SN per age range and percentage
age_demo = pd.DataFrame({'Total Count': age_count,
                         'Percentage of Players': age_percent})

# Clean data formatting for percentage columns
age_demo['Percentage of Players'] = age_demo['Percentage of Players'].astype(float).map('{:,.2f}%'.format)

# Display DataFrame sorted by Age Ranges index with applied style
age_demo.sort_index().style.set_table_styles(styles)

## Purchasing Analysis (Age)

* Bin the purchase_data data frame by age


* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. in the table below


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [7]:
# Create DataFrame with just Purchase ID, SN and Price colum data and group by Age Ranges
age_purchases = purchase_data[['Purchase ID','SN','Price','Age Ranges']].groupby(['Age Ranges'])

# Calculate counts, mean, sum and count of unique purchase for Age Demographics
age_purchase_count = age_purchases['Purchase ID'].count()
age_avg_purchase = age_purchases['Price'].mean()
age_total_purchase = age_purchases['Price'].sum()
age_unique_players = age_purchases['SN'].nunique()
age_avg_total = age_total_purchase / age_unique_players

# Create Age Demo DataFrame
age_demo = pd.DataFrame({'Purchase Count': age_purchase_count,
                         'Average Purchase Price': age_avg_purchase,
                         'Total Purchase Value': age_total_purchase,
                         'Avg Total Purchase per Person': age_avg_total})

# Clean data formatting for currency columns
age_demo['Average Purchase Price'] = age_demo['Average Purchase Price'].astype(float).map(
    '${:,.2f}'.format)
age_demo['Total Purchase Value'] = age_demo['Total Purchase Value'].astype(float).map(
    '${:,.2f}'.format)
age_demo['Avg Total Purchase per Person'] = age_demo['Avg Total Purchase per Person'].astype(float).map(
    '${:,.2f}'.format)

# Display Age Demographics frame with applied style
age_demo.style.set_table_styles(styles)

## Top Spenders

* Run basic calculations to obtain the results in the table below


* Create a summary data frame to hold the results


* Sort the total purchase value column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame

In [8]:
# Create DataFrame with Purchase ID, Price and group by SN
spender_purchases = purchase_data[['Purchase ID','SN','Price']].groupby(['SN'])

# Calculate counts, mean, sum of unique purchase for Top Spenders
spender_purchase_count = spender_purchases['Purchase ID'].count()
spender_avg_purchase = spender_purchases['Price'].mean()
spender_total_purchase = spender_purchases['Price'].sum()

# Create Top Spenders DataFrame
top_spenders = pd.DataFrame({'Purchase Count': spender_purchase_count,
                             'Average Purchase Price': spender_avg_purchase,
                             'Total Purchase Value': spender_total_purchase})

# Sort DataFrame by Total Purchase Value
top_spenders = top_spenders.sort_values('Total Purchase Value', ascending=False)

# Clean data formatting for currency columns
top_spenders['Average Purchase Price'] = top_spenders['Average Purchase Price'].astype(float).map(
    '${:,.2f}'.format)
top_spenders['Total Purchase Value'] = top_spenders['Total Purchase Value'].astype(float).map(
    '${:,.2f}'.format)

# Display preview of DataFrame with applied style
top_spenders.head().style.set_table_styles(styles)

## Most Popular Items

* Retrieve the Item ID, Item Name, and Item Price columns


* Group by Item ID and Item Name. Perform calculations to obtain purchase count, item price, and total purchase value


* Create a summary data frame to hold the results


* Sort the purchase count column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame

In [9]:
# Create DataFrame with Purchase ID, Price and group by Item ID and Item Name
item_purchases = purchase_data[['Purchase ID','Item ID','Item Name','Price']].groupby(['Item ID','Item Name'])

# Calculate counts and sum of purchases and prices for Most Popular Items
item_count = item_purchases['Item ID'].count()
item_price = item_purchases['Price'].mean()
total_purchase = item_purchases['Price'].sum()

# Create Most Popular Items DataFrame
most_pop_items = pd.DataFrame({'Purchase Count': item_count,
                               'Item Price': item_price,
                               'Total Purchase Value': total_purchase})

# Sort DataFrame by Purchase Count
most_pop_items_by_count = most_pop_items.sort_values('Purchase Count', ascending=False)

# Clean data formatting for currency columns
most_pop_items_by_count['Item Price'] = most_pop_items_by_count['Item Price'].astype(float).map(
    '${:,.2f}'.format)
most_pop_items_by_count['Total Purchase Value'] = most_pop_items_by_count['Total Purchase Value'].astype(float).map(
    '${:,.2f}'.format)

# Display preview of DataFrame with applied style
most_pop_items_by_count.head().style.set_table_styles(styles)

## Most Profitable Items

* Sort the above table by total purchase value in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the data frame

In [10]:
# Create new DataFrame for Most Popular Items and sort by Total Purchase Value descending
most_pop_items_by_total = most_pop_items.sort_values('Total Purchase Value', ascending=False)

# Clean data formatting for currency columns
most_pop_items_by_total['Item Price'] = most_pop_items_by_total['Item Price'].astype(float).map(
    '${:,.2f}'.format)
most_pop_items_by_total['Total Purchase Value'] = most_pop_items_by_total['Total Purchase Value'].astype(float).map(
    '${:,.2f}'.format)

# Display preview of DataFrame with applied style
most_pop_items_by_total.head().style.set_table_styles(styles)